// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hijimoxudzexpqmhjhwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhpamltb3h1ZHpleHBxbWhqaHdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NDU3MTcsImV4cCI6MjA2MTIyMTcxN30.AZYcsiyFy_EAt5owrYUia2FzAkNU08gul_N8YCeKcgc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);